# It is good practice when running analyses to save various settings outside the scripts, and call them in.
# Each time you run an analysis, save a copy of the .yml file used to run it. That way you can be sure what settings you used, even if you change them over time.
# ***** APPLIES TO ALL MODELS *****
# -> hrf information
hrf:
  pars: [1,1,0]         # Default parameters 
  deriv_bound: [0,10]   # If fitting the HRF these are the bounds (for hrf[1])
  disp_bound: [0,0]     # Generally advised to fix the dispersion value. Messing with this can get complex as you risk confounding inhibitory components 

# -> Generic fitting information
xtol: 1e-4 #fitting tolerance
ftol: 1e-4
grid_nr: 20         #number of items in grid
rsq_threshold: 0.1  # 
#
TR: 1.5
#
filter_predictions : False # Other options to do filtering...
n_jobs : 4 # For paralellisation, how many jobs to split off into
n_batches : 10 # For paralellisation at grid stage...
# ***** APPLIES TO PRF MODELS *****

# screen settings
screen_size_cm: 39.3
screen_distance_cm: 196
dm_edges_clipping: [0,0,0,0] # what to clip from design matrix
scr_shot_path : './screen_shots'
#unit volume RFs
normalize_RFs: False

#DM size in pixels (n_pix x n_pix) (has to be divisor of 1080)
n_pix: 100
eps: 1e-1

fixed_grid_baseline : 0
# set prf amplitude
bold_bsl: [0,0]
prf_ampl: [0,1]
#Constraints
constraints : False # Determines which fitter is used. None is fastere (lGBFS), than [] (trust-constrained)


save_grids : True # Save the outputs of the grid stage?

# set prf amplitude
bold_bsl: [0,0]
css_exponent: [0.01,3]

# grids for normalization model (not used if model != norm)
use_previous_gaussian_fitter_hrf : True
norm:
  surround_amplitude_grid: [0.05,0.2,0.4,0.7,1,3]
  surround_size_grid: [5,8,12,18]
  neural_baseline_grid: [0,1,10,100]
  surround_baseline_grid: [0.1,1.0,10.0,100.0] # [1]
  surround_amplitude_bound: [0,1]
  neural_baseline_bound: [0,100]
  surround_baseline_bound: [0.000001,100] # [1]

css:
  css_exponent_grid: [0.05,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1,1.1]
  css_exponent_bound: [0.01,3]

dog:
  dog_surround_amplitude_grid: [0.05,0.1,0.25,0.5,0.75,1,2]
  dog_surround_size_grid: [3,5,8,11,14,17,20,23,26]
  surround_amplitude_bound: [0,1]
